# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  branches:
    staging:
      - step:
          name: Build
          deployment: Build
          script:
            - node -v
            - npm i
            - NUXT_TARGET=server npm run build
            - zip -r crypto.page-artifacts.zip .nuxt node_modules
            - echo 'copy artifacts to server'
            - pipe: atlassian/scp-deploy:1.2.1
               variables:
                  USER: $USER
                  SERVER: $SERVER
                  REMOTE_PATH: '/tmp/'
                  LOCAL_PATH: 'crypto.page-artifacts.zip'
                  EXTRA_ARGS: ['-r']
      
             

            
