# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

#image: sickp/alpine-sshd

pipelines:
  branches:
    master:
      - step:
          name: Deploy
          deployment: Build
          script:
            - pipe: atlassian/scp-deploy:1.2.1
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: '/tmp/'
                LOCAL_PATH: './deploy/*'
                EXTRA_ARGS: ['-r']
            - >- 
              ssh $USER@$SERVER 
              "export TG_BOT_ID=$TG_BOT_ID && 
              export TG_CHAT_ID=$TG_CHAT_ID && 
              export TG_TEXT_PREFIX=$TG_TEXT_PREFIX && 
              export DEPLOY_LOG_FILE=$DEPLOY_LOG_FILE && 
              /bin/bash /tmp/deploy.sh > $DEPLOY_LOG_FILE"

            
