export enum EErrorType {
  buyPostAccess = 'buyPostAccess',
  faucetTestMint = 'faucetTestMint',
  fetchTokens = 'fetchTokens',
  fetchNftTransactions = 'fetchNftTransactions',
  fetchNftTransactionDetails = 'fetchNftTransactionDetails',
  fetchOwnNfts = 'fetchOwnNfts',
  fetchTransactions = 'fetchTransactions',
  syncNftTransactions = 'syncNftTransactions',
  syncTransactions = 'syncTransactions',
  syncOwnNfts = 'syncOwnNfts',
  authUnsupportedChain = 'authUnsupportedChain',
  getDashboardList = 'getDashboardList',
  getDashboardDetails = 'getDashboardDetails',
  uploadingContentToArweave = 'uploadingContentToArweave',
  createPostTransaction = 'createPostTransaction',
}
